name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - ipython
  - pip
  - scipy
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - scipy
